#!/bin/sh

# (re)load sxhkd for keybinds
pkill sxhkd; sxhkd -c $HOME/.config/sxhkd/yaxwm-sxhkdrc &

# launch polybar
yaxwmbar &

# determine where to place the log file
logfile="$HOME/.yaxwmrc.log"
[ -d "$HOME/.local/share/xorg" ] && logfile="$HOME/.local/share/xorg/yaxwmrc.log"
: > "$logfile"

# Window manager configuration run as a compound command to
# redirect all output to a file instead of redirecting each command.
# Not needed but it's nice to be able to tell when there are errors.
{
	# workspace settings
	# ------------------------
	# initialize 10 workspaces (1-10)
	yaxwm -c set numws=9

	# default workspace values used when allocating new workspaces
	# can be applied to all existing workspaces when passed 'apply'
	yaxwm -c set ws=default apply layout=tile master=1 stack=3 gap=6 msplit=0.50 ssplit=0.50

	# rename workspace(s)
	#yaxwm -c set ws=1 name="1" ws=2 name="2"

	# change layout
	#yaxwm -c set ws=3 layout=grid

	# use some padding and gaps on the last workspace
	last=$(awk '/^numws:/ {print $2}' "$YAXWM_STATUS")
	yaxwm -c set ws="$last" pad left=100 right=100 top=50 bottom=50
	yaxwm -c set ws="$last" gap width=25


	# global settings
	# ---------------------
	# focus windows when receiving activation and enable focus-follows-mouse
	yaxwm -c set focus_urgent=true focus_mouse=true

	# place clients at the tail and ignore size hints on tiled windows
	yaxwm -c set tile_tohead=0 tile_hints=false

	# minimum width/height for resizing, and minimum allowed on-screen when moving
	yaxwm -c set win_minwh=50 win_minxy=10

	# disable gaps and borders in single window layouts
	yaxwm -c set smart_gap=true smart_border=true

	# define mouse mod and move/resize buttons
	yaxwm -c set mouse mod=super move=button1 resize=button3


	# borders
	# ---------
	# set border width and colour for each window state
	yaxwm -c set border width=2 colour focus='#458588' unfocus='#928374' urgent='#fb4934'

	# alternatively, enable split borders and colours
	#yaxwm -c set border width=5 outer=3 colour \
	#	focus='#6699cc' unfocus='#444444' urgent='#ee5555' \
	#	outer_focus='#222222' outer_unfocus='#222222' outer_urgent='#222222'


	# window rules
	# --------------
	# rule class, instance, and title regexes are always case insensitive

	# open window(s) on a specific workspace (assigned monitor)
	yaxwm -c rule class="^gimp$" ws=2

	# open window(s) on a monitor by number or name (active workspace on monitor)
	#yaxwm -c rule class="^chromium$" mon="HDMI-A-0"

	# open window(s) and use a callback function (defined in config.h)
	# eg. mpv --x11-name=albumart /path/to/media
	#yaxwm -c rule class="^mpv$" instance="^albumart$" float=true callback=albumart bw=0

	# open window(s) in a floating state
	yaxwm -c rule class="^(pavucontrol|lxappearance)$" float=true

	# open window(s) with sticky and floating enabled to view on all workspaces.
	yaxwm -c rule class="^stickyterm$" stick=true float=true w=1280 h=720

	# floating terminal
	yaxwm -c rule class="^floatst$" float=true

	# apply current rule set to all existing windows
	yaxwm -c rule apply all

} >> "$logfile" 2>&1 # append responses

# inform of any errors in a notification
if grep -q 'error:' "$logfile"; then
	hash notify-send && notify-send -t 0 -u critical "Yaxwmrc Has Errors" \
		"$(awk '/error:/ {sub(/^error: /, ""); gsub(/</, "\<"); print}' "$logfile")"
	exit 1
fi

exit 0
