#!/bin/sh

imagepreview() {
    chafa --fill=block --symbols=block -c 256 -s 80x"$2" "$1"
}

videopreview() {
    set -e
    ffmpeg -ss 00:00:10 -i "$1" -vframes 1 -q:v 2 /tmp/videopreview.jpg
    imagepreview /tmp/videopreview.jpg "$2"
    rm /tmp/videopreview.jpg
    set +e
}

audiopreview() {
    ffmpeg -i "$1" 2>&1 | grep Duration | tr ',' '\n' | sed 's/^\ *//'
}

pdfpreview() {
    pdftohtml "$1" -i -f 1 -l 3 -stdout >/tmp/pdfpage.html
    w3m /tmp/pdfpage.html -dump
    rm /tmp/pdfpage.html
}

elsepreview() {
    bat --color=always --theme=base16 -p "$1"
}

case "$1" in
    *.tar*) tar tf "$1" ;;
    *.zip) unzip -l "$1" ;;
    *.rar) unrar l "$1" || file "$1" ;;
    *.7z) 7z l "$1" ;;
    *.pdf) pdftotext "$1" - || pdfpreview "$1" ;;
    *.png | *.jpg | *.JPG | *.jpeg | *.gif | *.webp) imagepreview "$1" "$2" ;;
    *.mp4 | *.mkv | *.mov | *.avi | *.m4v | *.webm) videopreview "$1" "$2" ;;
    *.mp3) audiopreview "$1" ;;
    *) elsepreview "$1" ;;
esac
