#!/bin/sh

# merge xresources
xrdb -merge ~/.config/X11/Xresources

# remap caps to esc
setxkbmap -option caps:escape

# set cursor
xsetroot -cursor_name left_ptr

# increase key repeat rate
xset r rate 250 30

# set wallpaper
setwall &

# notification daemon
dunst &

# start compositor
picom &

# hide mouse when typing
xbanish &

# clipboard manager
clipmenud &

# start xautolock with slock
xautolock -time 30 -locker slock &

# dbus session
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"; then
       eval `dbus-launch --sh-syntax --exit-with-session`
fi

# start wm
while true; do
    dwm 2> ~/.cache/dwm.log
done
